### ISSUE TITLE
Thread Leak?

### ISSUE THREAD

**Issue by DanielJonesEB** [cloudfoundry-incubator/switchboard#14]
Hi all,

I'm running SCF, deploying with Helm, which all worked fine. After a while my UAA was unhappy, and I traced it back to the Switchboard process on the MySQL pod. I've no idea if Switchboard was responsible, or just the first thing to fail due to the lack of file descriptors/whatever.

It seems that there's some sort of resource leak? 

```
{"timestamp":"1559839050.040677309","source":"/var/vcap/packages/switchboard/bin/switchboard","message":"/var/vcap/packages/switchboard/bin/switchboard.New active backend","log_l
evel":1,"data":{"backend":{"host":"mysql-0.mysql-set.uaa.svc.cluster.local","port":13306,"status_port":9200,"healthy":true,"name":"backend-0","currentSessionCount":0}}}
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f559a35ef67 m=26 sigcode=18446744073709551610

goroutine 0 [idle]:

goroutine 2 [running]:
runtime.systemstack_switch()
        /var/vcap/packages/golang/src/runtime/asm_amd64.s:298 fp=0xc42004c788 sp=0xc42004c780 pc=0x45bde0
runtime.gcStart(0x0, 0x2, 0x1a7af62145b4, 0xc400000000)
        /var/vcap/packages/golang/src/runtime/mgc.go:1319 +0x2c1 fp=0xc42004c7a8 sp=0xc42004c788 pc=0x41a301
runtime.forcegchelper()
        /var/vcap/packages/golang/src/runtime/proc.go:251 +0x6d fp=0xc42004c7e0 sp=0xc42004c7a8 pc=0x42eedd
runtime.goexit()
        /var/vcap/packages/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42004c7e8 sp=0xc42004c7e0 pc=0x45ea11
created by runtime.init.4
        /var/vcap/packages/golang/src/runtime/proc.go:234 +0x35
```

I tried starting it manually, and got this:

```
# ./switchboard_ctl start
2019-06-06 18:10:17 +0000 ----- Starting switchboard...
------------ STARTING switchboard_ctl at Thu Jun  6 18:10:17 UTC 2019 --------------
------------ STARTING switchboard_ctl at Thu Jun  6 18:10:17 UTC 2019 --------------
su: failed to execute /bin/bash: Resource temporarily unavailable
```

Apparently there are no ulimits set:

```
# ulimit
unlimited
```

Recreating the pod didn't help, but recreating the whole node did. Does this suggest the culprit could have been anything on that node?

**Comment by crhino** [comment]
Hi @DanielJonesEB,

I spent some time looking into this this morning. My thoughts on this are as follows:

```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
```
This failure implies that switchboard was attempting to create a new POSIX thread, which means that all of the other threads were blocked for some reason (either syscalls or cgo calls). Why all other POSIX threads were blocked is hard to tell. I refer to [this issue](https://github.com/golang/go/issues/24484) that has a similar error and discussion around these same topics.

```
$ ulimit
unlimited
```
I believe that even though `ulimit` says unlimited here, there is still a maximum limit on the number of threads able to be created. Specifically, threads tend to fall into the same limits as number of processes. It is certainly possible that your node had reached the maximum number of PIDs allowed and could not continue.

See below for example output of `ulimit` and `sysctl`:

```
$ ulimit
unlimited
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 29774
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 29774
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
$ sysctl kernel.pid_max
kernel.pid_max = 32768
```

Given the fact that attempting to restart the switchboard process itself resulted in a resource issue, i.e.:

```
# ./switchboard_ctl start
2019-06-06 18:10:17 +0000 ----- Starting switchboard...
------------ STARTING switchboard_ctl at Thu Jun  6 18:10:17 UTC 2019 --------------
------------ STARTING switchboard_ctl at Thu Jun  6 18:10:17 UTC 2019 --------------
su: failed to execute /bin/bash: Resource temporarily unavailable
```

and the fact that recreating the pod did not help, I am inclined to think something outside of the switchboard process was responsible for the resource contention.

Have you continued to observe this or similar issues?
